import React from "react";
import Link from "next/link";
import jsPDF from "jspdf";

const ResultsPage = ({
  score,
  totalQuestions,
  timeLeft,
  startExamHandler,
  subject,
}) => {
  const percentage = Math.round((score / totalQuestions) * 100);
  const performanceMessage =
    percentage >= 80
      ? "Excellent work! 🎉"
      : percentage >= 60
        ? "Good effort! 👍"
        : percentage >= 40
          ? "Keep practicing! 💪"
          : "Try again! 📖";

  const downloadPDF = () => {
    const doc = new jsPDF();
    const date = new Date().toLocaleDateString();

    // Set colors
    doc.setTextColor(79, 70, 229); // Indigo-600
    doc.setFontSize(24);
    doc.text("SmartExam Result Certificate", 105, 30, { align: "center" });

    doc.setTextColor(100);
    doc.setFontSize(14);
    doc.text(`Subject: ${subject}`, 105, 45, { align: "center" });
    doc.text(`Date Taken: ${date}`, 105, 55, { align: "center" });

    doc.setDrawColor(79, 70, 229);
    doc.line(20, 65, 190, 65);

    doc.setTextColor(30);
    doc.setFontSize(18);
    doc.text("Performance Summary", 20, 80);

    doc.setFontSize(14);
    doc.text(`Score: ${score} / ${totalQuestions}`, 20, 95);
    doc.text(`Percentage: ${percentage}%`, 20, 105);
    doc.text(`Performance: ${performanceMessage.replace(/[\uD800-\uDBFF][\uDC00-\uDFFF]/g, "")}`, 20, 115);

    doc.setTextColor(150);
    doc.setFontSize(10);
    doc.text("Generated by SmartExam - Quality CBT Solutions", 105, 280, { align: "center" });

    doc.save(`${subject}_Exam_Result.pdf`);
  };

  return (
    <div className="text-center">
      <h2 className="text-4xl font-extrabold text-indigo-700 mb-6">
        {timeLeft === 0 ? "Time's Up! Exam Submitted" : "Exam Complete!"}
      </h2>

      <div className="bg-gradient-to-br from-indigo-50 to-blue-50 border-4 border-indigo-400 p-8 rounded-2xl shadow-2xl inline-block max-w-full w-96 mb-6">
        <p className="text-xl text-gray-700 mb-4 font-semibold">
          Your Final Score:
        </p>
        <p className="text-7xl font-extrabold text-indigo-800">
          {score} / {totalQuestions}
        </p>
        <p className="text-2xl font-bold text-emerald-600 mt-4">
          {percentage}%
        </p>
        <p className="text-lg font-semibold text-gray-800 mt-3">
          {performanceMessage}
        </p>
      </div>

      <p className="text-gray-600 mt-8 text-sm max-w-md mx-auto">
        Great job completing the {subject} exam! Your score has been recorded.
      </p>

      <div className="flex flex-wrap gap-4 justify-center mt-8">
        <button
          onClick={startExamHandler}
          className="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2 px-6 rounded-lg transition duration-300 shadow-md transform hover:scale-105"
        >
          Retake Exam
        </button>
        <button
          onClick={downloadPDF}
          className="bg-emerald-600 hover:bg-emerald-700 text-white font-semibold py-2 px-6 rounded-lg transition duration-300 shadow-md transform hover:scale-105 flex items-center gap-2"
        >
          Download Result (PDF)
        </button>
        <Link href="/exam">
          <button className="bg-gray-300 hover:bg-gray-400 text-gray-800 font-semibold py-2 px-6 rounded-lg transition duration-300 shadow-md transform hover:scale-105">
            Choose Another Subject
          </button>
        </Link>
      </div>
    </div>
  );
};

export default ResultsPage;
